---
language: ruby
notifications:
  email:
  - drbrain@segment7.net
  - ljjarvis@gmail.com
  - knu@idaemons.org
sudo: false
# bundler is missing for jruby-head in travis-ci
# https://github.com/travis-ci/travis-ci/issues/5861
before_install: gem install --conservative bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1
- 2.2
- 2.3.1
- ruby-head
- jruby-1.7.26
- jruby-9.1.5.0
- jruby-head
script: rake test
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
