before_script:
  - gem install hoe --no-rdoc --no-ri
  - gem install rdoc --no-rdoc --no-ri
  - gem install minitest --no-rdoc --no-ri
  - rake travis_deps
  - EDITOR=true rake config_hoe check_manifest
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email:
    - drbrain@segment7.net
